name: streamful
description: This package provides widgets and utilities to deal with streams.
version: 1.0.1
repository: https://github.com/dariof28/streamful

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
