name: streamful
description: Widgets and utilities to deal with streams
version: 0.2.0
repository: https://github.com/dariof28/streamful

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
